--[[
	© 2018 Thriving Ventures AB do not share, re-distribute or modify

	without permission of its author (gustaf@thrivingventures.com).
]]

--
--	Default ranks.
--	serverguard.ranks:AddRank(unique, name, immunity, color, texture, data)
--

serverguard.ranks:AddRank("user", "Игрок", 0, Color(100, 150, 245, 255), "icon16/user.png", {
	Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 0,
		["Ragdolls"] = 0,
		["Npcs"] = 0,
		["Tools"] = {},
		["Sents"] = 0,
		["Emitters"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
	},

	phys_color = Color(77, 255, 255)
});

--
--	Administrator groups.
--
serverguard.ranks:AddRank("commander", "Коммандер", 15, Color(117, 0, 211), "icon16/cog.png", {
	Permissions = {
		["Sandbox settings"] = false,
		["Set Rank"] = false,
		["Edit Ranks"] = false,
		["Manage Players"] = false,
		["Extinguish"] = false,
		["Invisible"] = true,
		["Slay"] = false,
		["NPC Target"] = true,
		["Ban"] = false,
		["Model"] = true,
		["Set rank control"] = true,
		["Edit Ban"] = false,
		["Unban"] = false,
		["Manage Plugins"] = false,
		["Slap"] = false,
		["Set Armor"] = true,
		["Strip Weapons"] = false,
		["Map Restart"] = false,
		["Clear Decals"] = false,
		["Send"] = true,
		["Give Ammo"] = true,
		["Ragdoll"] = false,
		["Goto"] = false,
		["Quick Menu"] = false,
		["Kick"] = false,
		["Spectate"] = false,
		["Screencap"] = false,
		["Ignite"] = false,
		["Server Logs"] = false,
		["Map"] = false,
		["Respawn"] = true,
		["Set Health"] = true,
		["Bring"] = true,
		["Noclip"] = true,
		["Manage Restrictions"] = false,
		["Give Weapon"] = false,
		["Play Song"] = false,
		["Analytics"] = false,
		["God mode"] = true,
		["Mute"] = false,
		["Announce"] = false,
		["Freeze"] = false,
		["Rcon"] = false,
		["Admin"] = true,
		["Superadmin"] = false,
		["Manage Prop-Protection"] = false,
		["Bypass Prop-Protection"] = false,
		["Physgun Player"] = false,
		["Freeze Props"] = false,
		["Manage MOTD"] = false,
		["Manage Reports"] = false,
		["Bypass Prop Deletion"] = false,
		["Respond to Help Requests"] = false,
		["Return"] = true,
		["Go Incognito"] = false,
		["Admin Chat"] = false,
	},

Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 30,
		["Ragdolls"] = 0,
		["Npcs"] = 10,
		["Tools"] = {},
		["Sents"] = 0,
		["Balloons"] = 0,
		["Buttons"] = 0,
		["Dynamite"] = 0,
		["Effects"] = 0,
		["Emitters"] = 0,
		["Hoverballs"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
		["Thrusters"] = 0,
		["Wheels"] = 0,
	},

	phys_color = Color(77, 255, 255)
});

serverguard.ranks:AddRank("euclid", "Евклид", 20, Color(117, 0, 211), "icon16/bullet_orange.png", {

	Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 0,
		["Ragdolls"] = 0,
		["Npcs"] = 0,
		["Tools"] = {},
		["Sents"] = 0,
		["Emitters"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
	},

	Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 0,
		["Ragdolls"] = 0,
		["Npcs"] = 0,
		["Tools"] = {},
		["Sents"] = 0,
		["Balloons"] = 0,
		["Buttons"] = 0,
		["Dynamite"] = 0,
		["Effects"] = 0,
		["Emitters"] = 0,
		["Hoverballs"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
		["Thrusters"] = 0,
		["Wheels"] = 0,
	},

	phys_color = Color(77, 255, 255)
});


serverguard.ranks:AddRank("keter", "Кетер", 30, Color(117, 0, 211), "icon16/bullet_red.png", {
	Permissions = {
		["Sandbox settings"] = false,
		["Set Rank"] = false,
		["Edit Ranks"] = false,
		["Manage Players"] = false,
		["Extinguish"] = false,
		["Invisible"] = true,
		["Slay"] = false,
		["NPC Target"] = true,
		["Ban"] = false,
		["Edit Ban"] = false,
		["Unban"] = false,
		["Manage Plugins"] = false,
		["Slap"] = false,
		["Set Armor"] = false,
		["Strip Weapons"] = false,
		["Map Restart"] = false,
		["Clear Decals"] = false,
		["Send"] = false,
		["Give Ammo"] = false,
		["Ragdoll"] = false,
		["Goto"] = false,
		["Quick Menu"] = false,
		["Kick"] = false,
		["Spectate"] = false,
		["Screencap"] = false,
		["Ignite"] = false,
		["Server Logs"] = false,
		["Map"] = false,
		["Respawn"] = false,
		["Set Health"] = false,
		["Bring"] = true,
		["Noclip"] = true,
		["Manage Restrictions"] = false,
		["Give Weapon"] = false,
		["Play Song"] = false,
		["Analytics"] = false,
		["God mode"] = true,
		["Mute"] = false,
		["Announce"] = false,
		["Freeze"] = false,
		["Rcon"] = false,
		["Admin"] = false,
		["Superadmin"] = false,
		["Manage Prop-Protection"] = false,
		["Bypass Prop-Protection"] = false,
		["Physgun Player"] = false,
		["Freeze Props"] = false,
		["Manage MOTD"] = false,
		["Manage Reports"] = false,
		["Bypass Prop Deletion"] = false,
		["Respond to Help Requests"] = false,
		["Return"] = false,
		["Go Incognito"] = false,
		["Admin Chat"] = false,
	},
	Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 0,
		["Ragdolls"] = 0,
		["Npcs"] = 0,
		["Tools"] = {},
		["Sents"] = 0,
		["Emitters"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
	},

	Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 0,
		["Ragdolls"] = 0,
		["Npcs"] = 0,
		["Tools"] = {},
		["Sents"] = 0,
		["Balloons"] = 0,
		["Buttons"] = 0,
		["Dynamite"] = 0,
		["Effects"] = 0,
		["Emitters"] = 0,
		["Hoverballs"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
		["Thrusters"] = 0,
		["Wheels"] = 0,
	},

	phys_color = Color(77, 255, 255)
});


serverguard.ranks:AddRank("afina", "Афина", 40, Color(117, 0, 211), "icon16/bullet_blue.png", {
	Permissions = {
		["Sandbox settings"] = false,
		["Set Rank"] = false,
		["Edit Ranks"] = false,
		["Manage Players"] = false,
		["Extinguish"] = true,
		["Invisible"] = true,
		["Slay"] = false,
		["NPC Target"] = true,
		["Ban"] = false,
		["Edit Ban"] = false,
		["Unban"] = false,
		["Manage Plugins"] = false,
		["Slap"] = false,
		["Set Armor"] = true,
		["Strip Weapons"] = true,
		["Map Restart"] = false,
		["Clear Decals"] = true,
		["Send"] = true,
		["Give Ammo"] = false,
		["Ragdoll"] = false,
		["Goto"] = false,
		["Quick Menu"] = false,
		["Kick"] = true,
		["Spectate"] = true,
		["Screencap"] = false,
		["Ignite"] = true,
		["Server Logs"] = false,
		["Map"] = false,
		["Respawn"] = true,
		["Set Health"] = true,
		["Bring"] = true,
		["Noclip"] = true,
		["Manage Restrictions"] = false,
		["Give Weapon"] = true,
		["Play Song"] = false,
		["Analytics"] = false,
		["God mode"] = true,
		["Mute"] = false,
		["Announce"] = false,
		["Freeze"] = false,
		["Rcon"] = false,
		["Admin"] = true,
		["Model"] = true,
		["Superadmin"] = false,
		["Manage Prop-Protection"] = false,
		["Bypass Prop-Protection"] = false,
		["Physgun Player"] = false,
		["Freeze Props"] = false,
		["Manage MOTD"] = false,
		["Manage Reports"] = false,
		["Bypass Prop Deletion"] = false,
		["Respond to Help Requests"] = false,
		["Return"] = false,
		["Go Incognito"] = false,
		["Admin Chat"] = true,
	},

	Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 15,
		["Ragdolls"] = 0,
		["Npcs"] = 10,
		["Tools"] = {},
		["Sents"] = 0,
		["Balloons"] = 0,
		["Buttons"] = 0,
		["Dynamite"] = 0,
		["Effects"] = 0,
		["Emitters"] = 0,
		["Hoverballs"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
		["Thrusters"] = 0,
		["Wheels"] = 0,
	},

	phys_color = Color(77, 255, 255)
});


serverguard.ranks:AddRank("thaumiel", "Таумиель", 50, Color(117, 0, 211), "icon16/bullet_black.png", {
	Permissions = {
		["Sandbox settings"] = false,
		["Set Rank"] = false,
		["Edit Ranks"] = false,
		["Manage Players"] = false,
		["Extinguish"] = true,
		["Invisible"] = true,
		["Slay"] = true,
		["NPC Target"] = true,
		["Ban"] = true,
		["Edit Ban"] = false,
		["Unban"] = false,
		["Manage Plugins"] = false,
		["Slap"] = false,
		["Set Armor"] = true,
		["Strip Weapons"] = true,
		["Map Restart"] = false,
		["Clear Decals"] = false,
		["Send"] = true,
		["Give Ammo"] = false,
		["Ragdoll"] = false,
		["Goto"] = true,
		["Quick Menu"] = true,
		["Kick"] = true,
		["Spectate"] = true,
		["Screencap"] = false,
		["Ignite"] = true,
		["Server Logs"] = false,
		["Map"] = true,
		["Respawn"] = true,
		["Set Health"] = true,
		["Bring"] = true,
		["Noclip"] = true,
		["Manage Restrictions"] = false,
		["Give Weapon"] = false,
		["Play Song"] = false,
		["Analytics"] = false,
		["God mode"] = true,
		["Mute"] = false,
		["Announce"] = false,
		["Freeze"] = false,
		["Rcon"] = false,
		["Admin"] = true,
		["Model"] = true,
		["awarn_view"] = true,
		["awarn_warn"] = true,
		["Superadmin"] = false,
		["Manage Prop-Protection"] = false,
		["Bypass Prop-Protection"] = false,
		["Physgun Player"] = true,
		["Freeze Props"] = false,
		["Manage MOTD"] = false,
		["Manage Reports"] = false,
		["Bypass Prop Deletion"] = false,
		["Respond to Help Requests"] = false,
		["Return"] = true,
		["Go Incognito"] = false,
		["Admin Chat"] = true,
		["Ungag"] = true,
		["Unmute"] = true,
	},

	Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 20,
		["Ragdolls"] = 0,
		["Npcs"] = 10,
		["Tools"] = {},
		["Sents"] = 0,
		["Balloons"] = 0,
		["Buttons"] = 0,
		["Dynamite"] = 0,
		["Effects"] = 0,
		["Emitters"] = 0,
		["Hoverballs"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
		["Thrusters"] = 0,
		["Wheels"] = 0,
	},

	phys_color = Color(77, 255, 255)
});


serverguard.ranks:AddRank("apollo", "Аполлион", 60, Color(117, 0, 211), "icon16/bullet_pink.png", {
	Permissions = {
		["Sandbox settings"] = false,
		["Set Rank"] = false,
		["Edit Ranks"] = false,
		["Manage Players"] = false,
		["Extinguish"] = true,
		["Invisible"] = true,
		["Slay"] = true,
		["NPC Target"] = true,
		["Ban"] = true,
		["Edit Ban"] = false,
		["Unban"] = false,
		["Manage Plugins"] = false,
		["Slap"] = false,
		["Set Armor"] = true,
		["Strip Weapons"] = true,
		["Map Restart"] = false,
		["Clear Decals"] = false,
		["Send"] = true,
		["Give Ammo"] = false,
		["Ragdoll"] = false,
		["Goto"] = true,
		["Quick Menu"] = true,
		["Kick"] = true,
		["Spectate"] = true,
		["Screencap"] = false,
		["Ignite"] = true,
		["Server Logs"] = false,
		["Map"] = true,
		["Respawn"] = true,
		["Set Health"] = true,
		["Bring"] = true,
		["Noclip"] = true,
		["Manage Restrictions"] = false,
		["Give Weapon"] = false,
		["Play Song"] = false,
		["Analytics"] = false,
		["God mode"] = true,
		["Mute"] = false,
		["Announce"] = false,
		["Freeze"] = false,
		["Rcon"] = false,
		["Admin"] = true,
		["Model"] = true,
		["awarn_view"] = true,
		["awarn_warn"] = true,
		["Superadmin"] = false,
		["Manage Prop-Protection"] = false,
		["Bypass Prop-Protection"] = false,
		["Physgun Player"] = true,
		["Freeze Props"] = false,
		["Manage MOTD"] = false,
		["Manage Reports"] = false,
		["Bypass Prop Deletion"] = false,
		["Respond to Help Requests"] = false,
		["Return"] = true,
		["Go Incognito"] = false,
		["Admin Chat"] = true,
		["Ungag"] = true,
		["Unmute"] = true,
	},

Restrictions = {
		["Vehicles"] = 0,
		["Effects"] = 0,
		["Props"] = 80,
		["Ragdolls"] = 0,
		["Npcs"] = 25,
		["Tools"] = {},
		["Sents"] = 0,
		["Balloons"] = 0,
		["Buttons"] = 0,
		["Dynamite"] = 0,
		["Effects"] = 0,
		["Emitters"] = 0,
		["Hoverballs"] = 0,
		["Lamps"] = 0,
		["Lights"] = 0,
		["Thrusters"] = 0,
		["Wheels"] = 0,
	},

	phys_color = Color(77, 255, 255)
});



serverguard.ranks:AddRank("serverstaff", "Сенат Сервера", 70, Color(117, 0, 211), "icon16/eye.png", {
	Permissions = {
		["Sandbox settings"] = false,
		["Set Rank"] = true,
		["Edit Ranks"] = false,
		["Manage Players"] = false,
		["Extinguish"] = true,
		["Invisible"] = true,
		["Slay"] = true,
		["NPC Target"] = true,
		["Ban"] = true,
		["Edit Ban"] = true,
		["Unban"] = true,
		["Manage Plugins"] = false,
		["Slap"] = false,
		["Set Armor"] = true,
		["Strip Weapons"] = true,
		["Map Restart"] = true,
		["Clear Decals"] = true,
		["Send"] = true,
		["Give Ammo"] = true,
		["Ragdoll"] = false,
		["Goto"] = true,
		["Quick Menu"] = true,
		["Kick"] = true,
		["Spectate"] = true,
		["Screencap"] = false,
		["Ignite"] = true,
		["Server Logs"] = false,
		["Map"] = true,
		["Respawn"] = true,
		["Set Health"] = true,
		["Bring"] = true,
		["Noclip"] = true,
		["Manage Restrictions"] = false,
		["Give Weapon"] = true,
		["Play Song"] = true,
		["Analytics"] = false,
		["God mode"] = true,
		["Mute"] = true,
		["Announce"] = true,
		["Freeze"] = true,
		["Rcon"] = false,
		["Admin"] = true,
		["Model"] = true,
		["awarn_view"] = true,
		["awarn_warn"] = true,
		["Superadmin"] = false,
		["Manage Prop-Protection"] = false,
		["Bypass Prop-Protection"] = false,
		["Physgun Player"] = true,
		["Freeze Props"] = false,
		["Manage MOTD"] = false,
		["Manage Reports"] = false,
		["Bypass Prop Deletion"] = false,
		["Respond to Help Requests"] = false,
		["Return"] = true,
		["Go Incognito"] = false,
		["Admin Chat"] = true,
		["Ungag"] = true,
		["Unmute"] = true,
	},

	Restrictions = {
		["Vehicles"] = 4,
		["Effects"] = 0,
		["Props"] = 80,
		["Ragdolls"] = 4,
		["Npcs"] = 10,
		["Tools"] = {},
		["Sents"] = 8,
		["Balloons"] = 0,
		["Buttons"] = 15,
		["Dynamite"] = 6,
		["Effects"] = 0,
		["Emitters"] = 06,
		["Hoverballs"] = 0,
		["Lamps"] = 2,
		["Lights"] = 2,
		["Thrusters"] = 25,
		["Wheels"] = 25,
	},

	phys_color = Color(77, 255, 255)
});


serverguard.ranks:AddRank("moderator", "Модератор", 80, Color(117, 0, 211), "icon16/cup.png", {
	Permissions = {
		["Sandbox settings"] = false,
		["Set Rank"] = true,
		["Edit Ranks"] = false,
		["Manage Players"] = true,
		["Extinguish"] = true,
		["Invisible"] = true,
		["Slay"] = true,
		["NPC Target"] = true,
		["Ban"] = true,
		["Edit Ban"] = false,
		["Unban"] = true,
		["Model"] = true,
		["Set rank control"] = true,
		["Set Team"] = true,
		["Manage Plugins"] = false,
		["Slap"] = true,
		["Set Armor"] = true,
		["Strip Weapons"] = true,
		["Map Restart"] = true,
		["Clear Decals"] = true,
		["Send"] = true,
		["Give Ammo"] = true,
		["Ragdoll"] = true,
		["Goto"] = true,
		["Quick Menu"] = true,
		["Kick"] = true,
		["Spectate"] = true,
		["Screencap"] = false,
		["Ignite"] = true,
		["Server Logs"] = true,
		["Map"] = true,
		["Respawn"] = true,
		["Set Health"] = true,
		["Bring"] = true,
		["Noclip"] = true,
		["Manage Restrictions"] = false,
		["Give Weapon"] = true,
		["Play Song"] = true,
		["God mode"] = true,
		["Mute"] = true,
		["Announce"] = true,
		["Freeze"] = true,
		["Rcon"] = false,
		["Admin"] = true,
		["Superadmin"] = false,
		["awarn_view"] = true,
		["awarn_warn"] = true,
		["awarn_remove"] = true,
		["awarn_delete"] = true,
		["Physgun Player"] = true,
		["Freeze Props"] = true,
		["Manage MOTD"] = true,
		["Manage Reports"] = true,
		["Bypass Prop Deletion"] = true,
		["Respond to Help Requests"] = true,
		["Return"] = true,
		["Go Incognito"] = true,
		["Admin Chat"] = true,
		["Ungag"] = true,
		["Unmute"] = true,
	},

	Restrictions = {
		["Vehicles"] = 4,
		["Effects"] = 0,
		["Props"] = 80,
		["Ragdolls"] = 4,
		["Npcs"] = 15,
		["Tools"] = {},
		["Sents"] = 8,
		["Balloons"] = 0,
		["Buttons"] = 15,
		["Dynamite"] = 6,
		["Effects"] = 0,
		["Emitters"] = 06,
		["Hoverballs"] = 0,
		["Lamps"] = 2,
		["Lights"] = 2,
		["Thrusters"] = 25,
		["Wheels"] = 25,
	},

	phys_color = Color(77, 255, 255)
});

-- The founder rank is automatically granted all permissions, so no data needs to be set here.
serverguard.ranks:AddRank("founder", "Администратор", 99, Color(240, 0, 0), "icon16/color_wheel.png");
