-- -- To-do, add A LOT more of these
-- rp.AddTerm('DataNotLoaded', 'YOUR DATA IS NOT LOADED. PLEASE WAIT. IF THIS POPS UP AGAIN, PLEASE POST A BUG REPORT!')

-- rp.AddTerm('PleaseWaitX', 'Please wait # seconds to do that.')
-- rp.AddTerm('+Money', '+$#')
-- rp.AddTerm('-Money', '-$#')
-- rp.AddTerm('InvalidArg', 'Invalid argument.')
-- rp.AddTerm('CantFindPlayer', 'Couldn\'t find player #.')
-- rp.AddTerm('CannotAfford', 'You cannot afford this!')
-- rp.AddTerm('NeedVIP', 'You need VIP this! Type /upgrades to get it.')
-- rp.AddTerm('NeedToWait', 'You need to wait # seconds to do this!')
-- rp.AddTerm('ChangeJob', '# has become # #.')
-- rp.AddTerm('CannotChangeJob', 'You cannot change jobs while #!')
-- rp.AddTerm('ChangeName', '# has changed their name to #')
-- rp.AddTerm('Payday', 'Payday! You have been paid $#.')
-- rp.AddTerm('PaydayTax', 'Payday! You have been paid $# - $# tax.')
-- rp.AddTerm('PayDayUnemployed', 'You received no salary because you are unemployed!')
-- rp.AddTerm('PayDayMissed', 'You received no salary because you are arrested!')
-- rp.AddTerm('NotAllowedInSpawn', '# is not allowed in spawn!')
-- rp.AddTerm('LostKarma', 'You have lost # karma for #!')
-- rp.AddTerm('LostKarmaNR', 'You have lost # karma.')
-- rp.AddTerm('LostKarmaDrugs', 'You have lost # karma for doing drugs.')
-- rp.AddTerm('SpawnPropsSoFast', 'Please do not spawn props so fast.')
-- rp.AddTerm('RPNameShort', 'RP names must be longer than # characters.')
-- rp.AddTerm('RPNameLong', 'RP names must be shorter than # characters.')
-- rp.AddTerm('CannotRPName', 'You cannot change your RP name.')
-- rp.AddTerm('RPNameUnallowed', 'That name has unallowed characters (#).')
-- rp.AddTerm('SteamRPNameTaken', 'Your Steam name is already being used as someone\'s RP name, so we put a "1" after your name.')
-- rp.AddTerm('RPNameTaken', 'That RP name is already taken')
-- rp.AddTerm('EscapeDemotion', 'You tried to escape demotion. You failed, and have been demoted.')
-- rp.AddTerm('PlayerDemoted', '# has been demoted.')
-- rp.AddTerm('PlayerNotDemoted', '# has not been demoted.')
-- rp.AddTerm('DemotionStarted', '# has started a demotion vote for #.')
-- rp.AddTerm('DemotionReason', 'Please give a reason to demote.')
-- rp.AddTerm('DemoteReasonLong', 'Your demote reason must be below # characters.')
-- rp.AddTerm('DemoteSelf', 'You cannot demote yourself.')
-- rp.AddTerm('UnableToDemote', 'You cannot call a demote.')
-- rp.AddTerm('ChannelLimit', 'Choose a channel between 0 and 100.')
-- rp.AddTerm('ChannelSet', 'Channel set to #.')
-- rp.AddTerm('ChannelNotSet', 'You have not set your channe!')
-- rp.AddTerm('GiveMoneyLimit', 'Cannot give less than $1 away.')
-- rp.AddTerm('DropMoneyLimit', 'Cannot drop less than $1.')
-- rp.AddTerm('ChequeArg1', 'Invalid argument #1: recipient.')
-- rp.AddTerm('ChequeArg2', 'Invalid argument #2: amount.')
-- rp.AddTerm('PlayerGaveCash', '# has given you #.')
-- rp.AddTerm('YouGaveCash', 'You gave # #.')
-- rp.AddTerm('MustLookAtPlayer', 'You must be looking at a player.')

-- rp.AddTerm('HoesProfit', 'You have received $100 from your hoes.')
-- rp.AddTerm('CannotAffordHoe', '# cannot afford your services!')
-- rp.AddTerm('YouCannotAffordHoe', 'You cannot afford #\'s services!')
-- rp.AddTerm('GetCloser', 'You need to be closer to your target!')
-- rp.AddTerm('YouAreDead', 'You are dead!')
-- rp.AddTerm('NotAHoe', 'You are not a hoe.')
-- rp.AddTerm('NPCsDontFuck', 'You cannot fuck an NPC.')
-- rp.AddTerm('TargetFrozen', 'Your target is frozen.')
-- rp.AddTerm('WaitingForAnswer', 'Waiting for an answer.')
-- rp.AddTerm('TargetWontFuck', 'Your target does not wish to fuck.')
-- rp.AddTerm('TargetTooFar', 'Your target is too far away.')
-- rp.AddTerm('HoeTooFar', 'Your hoe is too far away.')
-- rp.AddTerm('+FuckCostPimp', '+ $# - 100 (Pimp\'s cut)')

-- rp.AddTerm('Warranted', '#\nReason: #\nOrdered by: #.')
-- rp.AddTerm('Wanted', '# \nReason: #\nOrdered by: #.')
-- rp.AddTerm('Arrested', '# has been arrested.')
-- rp.AddTerm('UnArrested', '# has been released from jail.')

-- rp.AddTerm('DoorLocked', 'Locked!')
-- rp.AddTerm('DoorUnlocked', 'Unlocked!')
-- rp.AddTerm('MaxDoors', 'You have reached the max number of owned door!')
-- rp.AddTerm('DoorBought', 'You have bought a door for #.')
-- rp.AddTerm('DoorOwnerAdded', '# has been added to your door.')
-- rp.AddTerm('DoorOwnerAddedYou', '# has added you to their door.')
-- rp.AddTerm('DoorOwnerRemoved', '# has been removed from your door.')
-- rp.AddTerm('DoorOwnerRemovedYou', '# has removed you from their door.')
-- rp.AddTerm('DoorSold', 'You have sold a door for #.')
-- rp.AddTerm('DoorTitleSet', 'Door title set.')
-- rp.AddTerm('OrgDoorEnabled', 'Org ownership enabled')
-- rp.AddTerm('OrgDoorDisabled', 'Org ownership disabled.')
-- rp.AddTerm('NoDoors', 'You have no doors to sell.')
-- rp.AddTerm('DoorsSold', 'You have sold # doors for #.')

-- rp.AddTerm('EventEnded', '# event has ended.')

-- rp.AddTerm('OrgDisbanded', '# has been disbanded!')
-- rp.AddTerm('OrgPlayerKicked', '# has been kicked from #.')
-- rp.AddTerm('OrgPlayerYoureKicked', 'You have been kicked from #.')
-- rp.AddTerm('OrgMustLeaveFirst', 'You need to leave your current organization to create a new one.')
-- rp.AddTerm('OrgNameShort', 'Please make your organization name longer than 2 characters.')
-- rp.AddTerm('OrgNameLong', 'Please make your organization name shorter than 20 characters.')
-- rp.AddTerm('OrgNameTaken', 'This name is already taken. Please choose another!')
-- rp.AddTerm('OrgCannotAffort', 'You cannot afford to create an organization.')
-- rp.AddTerm('OrgCreated', 'You have successfully created your organization.')
-- rp.AddTerm('OrgMOTDChanged', 'You\'ve changed your organization MoTD.')
-- rp.AddTerm('OrgColorChanged', 'You\'ve changed your organization color.')
-- rp.AddTerm('OrgPlayerQuit', '# has quit #!')
-- rp.AddTerm('OrgMemberLimit', 'You\'ve reached the limit of # org members!')
-- rp.AddTerm('OrgMemberJoined', '# has joined #.')

-- rp.AddTerm('MustBeMayorSetLaws', 'You must be the mayor to set laws!')
-- rp.AddTerm('MustBeMayorResetLaws', 'You must be the mayor to reset laws!')
-- rp.AddTerm('LotteryTax', 'You have received # in lottery taxes.')
-- rp.AddTerm('LotteryWinner', '# has won # in the lottery!')
-- rp.AddTerm('NoLottery', 'Nobody else entered the lottery, so your money was returned.')
-- rp.AddTerm('NoLotteryTax', 'You have received $0 in lottery taxes because nobody entered.')
-- rp.AddTerm('NotInLottery', 'You did not enter the lottery.')
-- rp.AddTerm('InLottery', 'You entered the lottery for #.')
-- rp.AddTerm('NoLotteryAll', 'Nobody entered the lottery.')
-- rp.AddTerm('CannotLottery', 'You\'re unable to start a lottery right now.')
-- rp.AddTerm('LottoCooldown', 'Please wait # seconds to start another lottery.')
-- rp.AddTerm('LottoCost', 'Please specify an entry cost ($#-$#).')
-- rp.AddTerm('LotteryStarted', 'A lottery has started!')

-- rp.AddTerm('CannotLockdown', 'You cannot start a lockdown right now.')
-- rp.AddTerm('LockdownStarted', 'The mayor has initiated a lockdown. Please return to your homes!')
-- rp.AddTerm('CannotUnlockdown', 'You cannot end a lockdown right now.')
-- rp.AddTerm('LockdownEnded', 'The lockdown has ended.')

-- rp.AddTerm('WarrantExpired', 'Your warrant has expired.')
-- rp.AddTerm('WantedPlayerNotFound', '# not found!')
-- rp.AddTerm('PlayerAlreadyWanted', '# is already wanted!')
-- rp.AddTerm('PlayerAlreadyWarranted', '# is already warranted!')
-- rp.AddTerm('PlayerNotWanted', '# is not wanted!')
-- rp.AddTerm('PlayerNotWarranted', '# is not warranted!')
-- rp.AddTerm('WarrantRequestAcc', 'Your warrant request was accepted.')
-- rp.AddTerm('WarrantRequestDen', 'Your warrant request was denied.')

-- rp.AddTerm('HitComplete', 'Hit on # complete.')
-- rp.AddTerm('YourHitComplete', 'You have been killed by a hitman.')
-- rp.AddTerm('HitTargetInvalid', 'You must choose a valid target!')
-- rp.AddTerm('CantHitYourself', 'You cannot put a hit on yourself!')
-- rp.AddTerm('CantHitHitman', 'You cannot put a hit on a hitman!')
-- rp.AddTerm('CantPlaceHit', 'Hitmen cannot place hits!')
-- rp.AddTerm('HitPriceLimit', 'Hit prices must be between # and #.')
-- rp.AddTerm('HitTimer', 'You cannot place another hit for # seconds.')
-- rp.AddTerm('MultiHit', 'You cannot place a hit on the same person twice in a row!')
-- rp.AddTerm('BountyIncrease', 'You increased the bounty on # by #.')
-- rp.AddTerm('HitPlaced', 'You have placed a hit on # for #.')
-- rp.AddTerm('HitmanFailed', 'You have failed as a hitman!')

-- rp.AddTerm('EmployeeChangedJob', 'Your employee has changed jobs!')
-- rp.AddTerm('EmployeeChangedJobYou', 'Your employer\'s contract has been terminated because you changed jobs!')
-- rp.AddTerm('EmployeeDied', 'Your employee has died!')
-- rp.AddTerm('EmployeeDiedYou', 'Your employer\'s contract has been terminated because you died!')
-- rp.AddTerm('EmployerDied', 'Your employer has died!')
-- rp.AddTerm('EmployerDiedYou', 'Your employee has been terminated because you died.')
-- rp.AddTerm('EmployeeLeft', 'Your employee has disconnected!')
-- rp.AddTerm('EmployerLeft', 'Your employer has disconnected!')
-- rp.AddTerm('PlayerNotHirable', '# is not hirable.')
-- rp.AddTerm('EmployeeTriedEmploying', 'You are seeking work currently. You cannot hire an employee!')
-- rp.AddTerm('HasEmployee', 'You already have an employee!')
-- rp.AddTerm('AlreadyEmployed', 'You\'re already employed!')
-- rp.AddTerm('CannotAffordEmployee', 'You cannot affort to hire anyone!')
-- rp.AddTerm('EmployRequestSent', '# has been sent your request for hire.')
-- rp.AddTerm('YouHired', 'You have hired # for #.')
-- rp.AddTerm('YouAreHired', '# has hired you for #.')
-- rp.AddTerm('EmployRequestDen', '# has denied your request for hire.')
-- rp.AddTerm('EmployeeFired', 'You have fired #.')
-- rp.AddTerm('EmployeeFiredYou', '# has fired you!')
-- rp.AddTerm('EmployeeQuit', '# has quit their job with you!')
-- rp.AddTerm('EmployeeQuitYou', 'You have quit for job for #.')

-- rp.AddTerm('CannotTool', 'Your rank cannot use the "#" tool!')
-- rp.AddTerm('DupeRestrictedEnts', 'You cannot spawn dupes containing these entities!')
-- rp.AddTerm('WhitelistFull', 'The whitelist is full #/750')
-- rp.AddTerm('CacheFull', 'The model precache is full #/100!')
-- rp.AddTerm('PropWhitelisted', '# has been whitelisted by #.')
-- rp.AddTerm('PropBlacklisted', '# has been blacklisted by #.')
-- rp.AddTerm('PPTargNotFound', 'Target not found!')
-- rp.AddTerm('UnsharedPropsYou', 'You have unshared your props with #.')
-- rp.AddTerm('UnsharedProps', '# has unshared their props with you.')
-- rp.AddTerm('SharedPropsYou', 'You have shared your props with #.')
-- rp.AddTerm('SharedProps', '# has shared their props with you.')
-- rp.AddTerm('PPGroupSet', '# has been set to group # by #.')
-- rp.AddTerm('PropNotWhitelisted', '# is not whitelisted!')

-- rp.AddTerm('NoPMResponder', 'There\'s nobody to respond to!')
-- rp.AddTerm('CannotDestroyWeapon', 'You cannot destroy this weapon!')

-- rp.AddTerm('YourEntDestroyed', 'Your # was destroyed!')
-- rp.AddTerm('InvalidURL', 'Invalid URL!')
-- rp.AddTerm('VideoFailed', 'Failed to load video: #.')
-- rp.AddTerm('FoodLimitReached', 'You have reached the food limit!')
-- rp.AddTerm('BoughtFoodProduction', 'You have paid # for food production.')
-- rp.AddTerm('SoldFoodNoProf', 'You sold some food and made no profit, but gained 3 Karma.')
-- rp.AddTerm('SoldFood', 'You sold some food and made # profit and gained 1 karma.')
-- rp.AddTerm('BoughtFood', 'You have purchased food for #.')
-- rp.AddTerm('ThereIsACook', 'There is a cook. You can\'t do this!')
-- rp.AddTerm('EmptyShipment', 'There is nothing in the shipment.')

-- rp.AddTerm('GCMessageLimit', 'Your message needs to be more than 1 character!')

-- rp.AddTerm('CantSuicideJail', 'You can\'t suicide in jail.')
-- rp.AddTerm('CantSuicideWanted', 'You can\'t suicide while wanted.')
-- rp.AddTerm('CantSuicideFrozen', 'You can\'t suicide while frozen.')
-- rp.AddTerm('CantSuicideLiveFor', 'You have too much to live for!')
-- rp.AddTerm('YouSuicided', 'You are a disgrace to your family!')

-- rp.AddTerm('CantPurchaseUpgrade', 'You cannot purchase this. #')

-- rp.AddTerm('RPItemBought', 'You bought # for #.')

-- rp.AddTerm('CantAdminCleanup', 'You cannot use admin cleanup!')

-- rp.AddTerm('MayorHasDied', 'The mayor has died!')
-- rp.AddTerm('YouWereBailed', '# has bailed you from jail!')

-- rp.AddTerm('ArmorLabProfit', 'You received $# from your armor lab.')
-- rp.AddTerm('BoughtArmor', 'You have bought armor for $#.')
-- rp.AddTerm('ArmorLabExploded', 'Your armor lab has exploded!')

-- rp.AddTerm('ChequeFound', 'You have found # in a cheque made out to you from #.')
-- rp.AddTerm('ChequeMadeTo', 'This cheque is made out to #.')
-- rp.AddTerm('ChequeTorn', 'You have torn up the cheque.')
-- rp.AddTerm('MoneyFound', 'You have found $#!')

-- rp.AddTerm('MustBeHobo', 'You need to be a hobo to use this!')
-- rp.AddTerm('AlreadyDisguised', 'You\'re already disguised!')
-- rp.AddTerm('GunLicenseActive', 'You have activated your gun license.')
-- rp.AddTerm('YouGotAIDS', 'You have contracted AIDS and will soon die.')
-- rp.AddTerm('YouGotHerpes', 'You have contracted herpes from an exposed needle.')
-- rp.AddTerm('STDCured', 'You have cured your sexually tramsitted diseases.')
-- rp.AddTerm('NowDisguised', 'You are now disguised as a #.')
-- rp.AddTerm('NowDisguisedTime', 'You are now disguised for # minutes as a #.')
-- rp.AddTerm('DisguiseWorn', 'Your disguise has worn off.')
-- rp.AddTerm('DisguiseLimit', 'You cannot disguise again for # minutes.')

-- rp.AddTerm('MedLabProfit', 'You received $# from your medic lab.')
-- rp.AddTerm('BoughtHealth', 'You have bought health for $#.')
-- rp.AddTerm('MedLabExploded', 'Your medic lab has exploded!')

-- rp.AddTerm('KeypadControlsX', 'This keypad controls # entities.')
-- rp.AddTerm('EntityControlledByX', 'This entity is controlled by # keypads.')

-- rp.AddTerm('VoteAlone', 'You have won the vote since you are alone in the server.')
-- rp.AddTerm('BannedFromJob', 'You are currently banned from becoming that team.')
-- rp.AddTerm('VotedTooSoon', 'Please wait # more seconds before voting to become this job.')
-- rp.AddTerm('AlreadyThisJob', 'You\'re already this job!')
-- rp.AddTerm('JobLimit', 'Team limit has already been reached.')
-- rp.AddTerm('RegisteredForVote', 'You have registered for the upcoming vote!')
-- rp.AddTerm('AlreadyVoting', 'Voting has already begun. You\'re too late!')
-- rp.AddTerm('JobNeedsAdmin', 'You must be moderator+ for this job.')
-- rp.AddTerm('JobNeedsSA', 'You must be SA+ for this job.')
-- rp.AddTerm('JobNeedsBanned', 'You need to be banned from the server to become this class')
-- rp.AddTerm('IncorrectJob', 'You are not currently the correct job to do that!')
-- rp.AddTerm('VoteStarted', 'Vote has been created.')
-- rp.AddTerm('CannotJob', 'You cannot change your job right now.')
-- rp.AddTerm('JobLenShort', 'Jobs must be more than # characters.')
-- rp.AddTerm('JobLenLong', 'Jobs must be less than # characters.')

-- rp.AddTerm('CannotPurchaseItem', 'You\'re not allowed to purchase this item.')
-- rp.AddTerm('ItemLimit', 'You\'ve reached the # limit.')
-- rp.AddTerm('ItemUnavailable', 'That item is unavailable.')
-- rp.AddTerm('UnableToItem', 'You were unable to purchase that item.')
-- rp.AddTerm('ShipmentCooldown', 'Please wait before spawning another shipment.')

-- rp.AddTerm('MedicExists', 'You cannot buy health because there are medics.')
-- rp.AddTerm('HealthIsFull', 'Your health is full already!')

-- rp.AddTerm('CannotDropWeapon', 'You cannot drop this weapon!')
-- rp.AddTerm('LookAtEntity', 'You need to be looking at an entity!')
-- rp.AddTerm('CannotSetPrice', 'You cannot set the price of this entity!')

-- rp.AddTerm('AnalProlapse', 'You have overexerted your anus and died from anal prolapse.')
-- rp.AddTerm('NoMorePoo', 'You have no more poo left!')
-- rp.AddTerm('NotARapist', 'You are not a rapist.')
-- rp.AddTerm('RapeNPC', 'You cannot rape an NPC.')
-- rp.AddTerm('RapeFailed', 'Rape attempt failed!')
-- rp.AddTerm('RapeAttempted', 'Someone has attempted to intrude your butthole.')
-- rp.AddTerm('Raped', 'You have intruded #\'s butthole.')
-- rp.AddTerm('YouAreRaped', 'Someone has intruded your butthole.')
-- rp.AddTerm('AnalProlapseShort', 'You have died from anal prolapse.')
-- rp.AddTerm('DickFellOff', 'Your dick has fallen off.')

-- rp.AddTerm('CannotVote', 'You cannot vote.')
-- rp.AddTerm('CantDoThis', 'You can\'t do this.')
-- rp.AddTerm('BaitingRule', 'Baiting is against the rules.')
-- rp.AddTerm('FoundNothing', 'You found nothing.')
-- rp.AddTerm('RobberyAttempt', 'You felt a slight movement in your pocket.')
-- rp.AddTerm('RobberyFailed', 'Robbery failed!')
-- rp.AddTerm('YouRobbed', 'You have stolen $#!')
-- rp.AddTerm('YouAreRobbed', 'Your pocket feels lighter.')

-- rp.AddTerm('NoteUpdated', 'Note text updated.')
-- rp.AddTerm('USENote', 'Press USE on your note to edit the text.')

-- rp.AddTerm('OrgYouAreStuck', 'You\'re stuck! >:)')
-- rp.AddTerm('OrgYourRank', '# has set your rank to \'#\'.')
-- rp.AddTerm('OrgSetRank', '# has been set to \'#\'.')
-- rp.AddTerm('OrgUnknownRank', 'Unknown rank \'#\'.')
-- rp.AddTerm('OrgRankRename', 'Rank \'#\' renamed to \'#\'.')
-- rp.AddTerm('OrgReorderLimit', 'You cannot reorder the highest and lowest ranks.')
-- rp.AddTerm('OrgRankUpdated', 'Rank \'#\' updated.')
-- rp.AddTerm('OrgMaxRanks', 'Maximum ranks reached.')
-- rp.AddTerm('OrgRankCreated', 'Rank \'#\' created.')
-- rp.AddTerm('OrgDeleteLimit', 'You cannot delete the top and bottom ranks.')
-- rp.AddTerm('OrgRankDelete', 'Rank \'#\' removed.')
-- rp.AddTerm('OrgBannerUpdated', 'Banner updated.')

-- rp.AddTerm('FadeDoorCreated', 'Fading door created.')
-- rp.AddTerm('FadeDoorCreatedExtra', 'Fading door created. Now, right click again to place a keypad.')
-- rp.AddTerm('InvalidPassword', 'Invalid password!')
-- rp.AddTerm('KeypadHoldLength', 'The hold length must be at least # seconds.')
-- rp.AddTerm('KeypadCreated', 'Keypad created.')

-- rp.AddTerm('SboxPropLimit', 'You\'ve hit the prop limit!')
-- rp.AddTerm('SboxXLimit', 'You\'ve hit the # limit!')

-- -- Entities folder
-- rp.AddTerm('ArcadeMachineUse', 'Get ready to play!')
-- rp.AddTerm('PlayerNotInJail', '# is not in jail.')
-- rp.AddTerm('PlayerFuckedBailing', 'You dumbass, the cops are hot on your tail now!')
-- rp.AddTerm('PlayerBailedPlayer', 'You have bailed # for #.')
-- rp.AddTerm('PlayerTookDonationBox', 'You have taken #.')
-- rp.AddTerm('YouDontOwnThis', 'You do not own this!')
-- rp.AddTerm('PlayerReceivedDonationBox', 'Someone has placed # in your donation box.')
-- rp.AddTerm('DrugLabExploded', 'Your drug lab has exploded!')
-- rp.AddTerm('PlayerNotWanted', 'This player is not wanted!')
-- rp.AddTerm('PlayerTookMoneyBasket', 'You have taken #.')
-- rp.AddTerm('PrinterIsFull', 'This printer\'s ink is already full!')
-- rp.AddTerm('PrinterRefilled', 'You\'ve refilled this printer for #.')
-- rp.AddTerm('PrinterExploded', 'Your money printer has exploded!')
-- rp.AddTerm('PlayerSoldDrugs', 'You\'ve sold your # for #.')

-- -- Weapons folder
-- rp.AddTerm('ArrestBatonBonus', 'You have received a # bonus for destroying this illegal entity.')
-- rp.AddTerm('ArrestBatonArrested', 'You\'ve been arrested by #.')
-- rp.AddTerm('ArrestBatonYouArrested', 'You arrested # and received 2 karma.')
-- rp.AddTerm('PlayerRangDoorbell', 'Someone has rang your doorbell.')
-- rp.AddTerm('KeysCooldown', 'Please wait to relock this door.')
-- rp.AddTerm('UnarrestBatonTarg', 'You\'ve been unarrested by #.')
-- rp.AddTerm('UnarrestBatonOwn', 'You unarrested #.')
-- rp.AddTerm('RiotShieldInSpawn', 'Please leave spawn to use the riot shield!')

-- rp.AddTerm('HatPurchased', 'You have purchased # for #.')
-- rp.AddTerm('HatEquipped', 'Hat equipped!')
-- rp.AddTerm('HatRemoved', 'Hat removed!')

-- rp.AddTerm('BURGHungerImmune', 'You\'re immune to hunger until you die, now!')
-- rp.AddTerm('BURGNotPeople', 'Silly burger, burgers aren\'t people!')

rp.AddTerm('NotEnoughTime', 'У вас отыграно слишком мало времени!')
rp.AddTerm('FireEx', 'Вы получили #$ за тушение пожара!')
rp.AddTerm('AxeNoFire', 'Для того чтобы дверь открылась, нужно чтобы было возгорание за ней или на ней!')
rp.AddTerm('HWGetMoney', 'Вы получили 30 кредитов!')
rp.AddTerm('Cantplant', 'Здесь гриб не приживётся.')
rp.AddTerm('LimiteMush', 'Достигнуто максимальное количество грибов')
rp.AddTerm('DataNotLoaded', 'ВАШИ ДАННЫЕ НЕ ЗАГРУЖЕНЫ. ПОЖАЛУЙСТА, ПОДОЖДИТЕ. ЕСЛИ ЭТО СЛУЧИТСЯ СНОВА, ПОЖАЛУЙСТА, СООБЩИТЕ НАМ ОБ ЭТОМ!')
rp.AddTerm('PleaseWaitX', 'Пожалуйста, подождите # секунд для этого.')
rp.AddTerm('+Money', '+$#')
rp.AddTerm('-Money', '-$#')
rp.AddTerm('InvalidArg', 'Недействительный аргумент.')
rp.AddTerm('CantFindPlayer', 'Невозможно найти игрока #.')
rp.AddTerm('CannotAfford', 'У Вас не хватает денег!')
rp.AddTerm('NeedVIP', 'Вам нужен VIP статус! Напишите /upgrades чтобы купить.')
rp.AddTerm('NeedToWait', 'Вам нужно подождать # секунд чтобы сделать это!')
rp.AddTerm('ChangeJob', '# теперь # #.')
rp.AddTerm('CannotChangeJob', 'Вы не можете сменить работу в течении #!')
rp.AddTerm('ChangeName', '# изменил имя на #')
rp.AddTerm('Payday', 'Зарплата! Вы получили $#.')
rp.AddTerm('PaydayTax', 'Зарплата! Вы получили $# - $# налог.')
rp.AddTerm('PayDayUnemployed', 'Вы не получили зарплату, потому что Вы - безработный!')
rp.AddTerm('PayDayMissed', 'Вы арестованы и не получили зарплату!')
rp.AddTerm('NotAllowedInSpawn', '# недопустимо на спавне!')
rp.AddTerm('LostKarma', 'Вы потеряли # очков Кармы, за #!')
rp.AddTerm('LostKarmaNR', 'Вы потеряли # очков Кармы.')
rp.AddTerm('LostKarmaDrugs', 'Вы потеряли # очков Кармы, за использование наркотиков.')
rp.AddTerm('SpawnPropsSoFast', 'Пожалуйста, спавните пропы не так быстро.')
rp.AddTerm('RPNameShort', 'RP имя должно быть длиннее # символов.')
rp.AddTerm('RPNameLong', 'RP имя должно быть короче # символов.')
rp.AddTerm('CannotRPName', 'Вы не можете изменить RP имя.')
rp.AddTerm('RPNameUnallowed', 'Это имя содержит недоступные символы (#).')
rp.AddTerm('SteamRPNameTaken', 'Ваше Steam-Имя уже используется кем-то, поэтому мы поставили "1" после Вашего имени.')
rp.AddTerm('RPNameTaken', 'Это RP имя уже взято ')
rp.AddTerm('EscapeDemotion', 'Вы пытаетесь избежать увольнения. У Вас не получилось, и Вы были уволены.')
rp.AddTerm('PlayerDemoted', '# был уволен.')
rp.AddTerm('PlayerNotDemoted', '# не был уволен.')
rp.AddTerm('DemotionStarted', '# начал голосование на увольнение #.')
rp.AddTerm('DemotionReason', 'Пожалуйста, укажите причину увольнения.')
rp.AddTerm('DemoteReasonLong', 'Ваша причина увольнения должна быть длиннее # characters.')
rp.AddTerm('DemoteSelf', 'Вы не можете уволить себя.')
rp.AddTerm('UnableToDemote', 'Вы не можете начать голосование.')
rp.AddTerm('ChannelLimit', 'Выберите канал от 0 до 100.')
rp.AddTerm('ChannelSet', 'Канал установлен на #.')
rp.AddTerm('ChannelNotSet', 'Вы не выставили свой канал!')
rp.AddTerm('GiveMoneyLimit', 'Вы не можете передать меньше чем $1.')
rp.AddTerm('DropMoneyLimit', 'Вы не можете выбросить меньше $1.')
rp.AddTerm('ChequeArg1', 'Недействительный аргумент #1: получатель.')
rp.AddTerm('ChequeArg2', 'Недействительный аргумент #2: количество.')
rp.AddTerm('PlayerGaveCash', '# дал Вам #.')
rp.AddTerm('YouGaveCash', 'Вы дали # #.')
rp.AddTerm('MustLookAtPlayer', 'Вы должны смотреть на игрока.')
rp.AddTerm('HoesProfit', 'Ты заработал $100 со своей шлюхи.')
rp.AddTerm('CannotAffordHoe', '# не может позволить себе Ваши услуги!')
rp.AddTerm('YouCannotAffordHoe', 'Вы не можете позволить себе услуги #!')
rp.AddTerm('GetCloser', 'Должен быть ближе к своей цели!')
rp.AddTerm('YouAreDead', 'Вы мертвы!')
rp.AddTerm('NotAHoe', 'Вы не проститутка.')
rp.AddTerm('NPCsDontFuck', 'Вы не можете заняться сексом с NPC.')
rp.AddTerm('TargetFrozen', 'Ваша цель заморожена.')
rp.AddTerm('WaitingForAnswer', 'В ожидании ответа.')
rp.AddTerm('TargetWontFuck', 'Ваша цель не желает заниматься сексом.')
rp.AddTerm('TargetTooFar', 'Ваша цель слишком далеко.')
rp.AddTerm('HoeTooFar', 'Ваша шлюха слишком далеко.')
rp.AddTerm('+FuckCostPimp', '+$# - $100 (доля сутенера)')
rp.AddTerm('Warranted', '#\nПричина: #\nОрдер на: #.')
rp.AddTerm('Wanted', '# \nПричина: #\nВыдал ордер: #.')
rp.AddTerm('Arrested', '# арестован.')
rp.AddTerm('UnArrested', '# выпущен из тюрьмы.')
rp.AddTerm('DoorLocked', 'Закрыто!')
rp.AddTerm('DoorUnlocked', 'Открыто!')
rp.AddTerm('MaxDoors', 'Вы достигли максимального количества купленных дверей!')
rp.AddTerm('DoorBought', 'Вы оплатили аренду за #.')
rp.AddTerm('DoorOwnerAdded', '# был добавлен в Вашу дверь.')
rp.AddTerm('DoorOwnerAddedYou', '# добавил Вас в свою дверь.')
rp.AddTerm('DoorOwnerRemoved', '# был удалён из Вашей двери.')
rp.AddTerm('DoorOwnerRemovedYou', '# удалил из своей двери.')
rp.AddTerm('DoorSold', 'Вы продали дверь за #.')
rp.AddTerm('DoorTitleSet', 'Название двери установленно .')
rp.AddTerm('OrgDoorEnabled', 'Владение организации разрешено')
rp.AddTerm('OrgDoorDisabled', 'Владение организации запрещено .')
rp.AddTerm('NoDoors', 'У Вас нет дверей на продажу.')
rp.AddTerm('DoorsSold', 'Вы продали # дверь за #.')
rp.AddTerm('EventEnded', '# Ивент закончился.')
rp.AddTerm('OrgDisbanded', '# был распущен!')
rp.AddTerm('OrgPlayerKicked', '# кикнут из организации #.')
rp.AddTerm('OrgPlayerYoureKicked', 'Вы были кикнуты из организации #.')
rp.AddTerm('OrgMustLeaveFirst', 'Вам нужно покинуть организацию чтобы создать новую.')
rp.AddTerm('OrgNameShort', 'Пожалуйста, сделайте название своей организации длиннее чем 2 буквы.')
rp.AddTerm('OrgNameLong', 'Пожалуйста, сделайте название своей организации короче чем чем 20 букв.')
rp.AddTerm('OrgNameTaken', 'Это имя уже занято. Пожалуйста выберите другое!')
rp.AddTerm('OrgCannotAffort', 'Вы не можете позволить себе создать организацию.')
rp.AddTerm('OrgCreated', 'Вы успешно создали свою организацию.')
rp.AddTerm('OrgMOTDChanged', 'Вы изменили вашу организацию MoTD.')
rp.AddTerm('OrgColorChanged', 'Вы изменили цвет организации.')
rp.AddTerm('OrgPlayerQuit', '# вышел из #!')
rp.AddTerm('OrgMemberLimit', 'Вы достигли максимального количество # членов в организации!')
rp.AddTerm('OrgMemberJoined', '# присоединился к #.')
rp.AddTerm('MustBeMayorSetLaws', 'Вы должны быть Мэром чтобы установить закон!')
rp.AddTerm('MustBeMayorResetLaws', 'Вы должны быть Мэром чтобы сбросить законы!')
rp.AddTerm('LotteryTax', 'Вы заработали # в лотереи.')
rp.AddTerm('LotteryWinner', '# выйграл # в лотерее!')
rp.AddTerm('NoLottery', 'Никто не учавствовал в лотерее, поэтому Ваши деньги были возвращены.')
rp.AddTerm('NoLotteryTax', 'Вы заработали $0 в лотереи потому, что никто не учавствовал.')
rp.AddTerm('NotInLottery', 'Вы не учавствуете в лотерее.')
rp.AddTerm('InLottery', 'Вы учавствуете в лотерее за  #.')
rp.AddTerm('NoLotteryAll', 'Никто не учавствует в лотерее.')
rp.AddTerm('CannotLottery', 'Вы не можешь учавствовать в лотерее прямо сейчас.')
rp.AddTerm('LottoCooldown', 'Пожалуйста, подождите # секунд чтобы начать лотерею')
rp.AddTerm('LottoCost', 'Пожалуйста, установ цену на вход ($#-$#).')
rp.AddTerm('LotteryStarted', 'Лотерея началась!')
rp.AddTerm('CannotLockdown', 'Комендантский час сейчас недоступен.')
rp.AddTerm('LockdownStarted', 'Мэр объявил комендантский час, вернитесь домой!')
rp.AddTerm('CannotUnlockdown', 'Вы не можете запустить комендантский час сейчас.')
rp.AddTerm('LockdownEnded', 'Комендантский час окончен.')
rp.AddTerm('WarrantExpired', 'Ваш ордер просрочен.')
rp.AddTerm('WantedPlayerNotFound', '# не найден!')
rp.AddTerm('PlayerAlreadyWanted', '# Уже разыскивается!')
rp.AddTerm('PlayerAlreadyWarranted', '# Уже есть ордер!')
rp.AddTerm('PlayerNotWanted', '# не разыскивается!')
rp.AddTerm('PlayerNotWarranted', 'На # нет ордера!')
rp.AddTerm('WarrantRequestAcc', 'Ваш ордер одобрен.')
rp.AddTerm('WarrantRequestDen', 'Ваш ордер был отклонён.')
rp.AddTerm('HitComplete', 'Заказ на # выполнен.')
rp.AddTerm('YourHitComplete', 'Вы были убит наёмным убийцей.')
rp.AddTerm('HitTargetInvalid', 'Вы должны выбрать правильную цель!')
rp.AddTerm('CantHitYourself', 'Вы не можете заказать себя!')
rp.AddTerm('CantHitHitman', 'Вы не можете заказать Наёмника!')
rp.AddTerm('CantPlaceHit', 'Наёмник не может делать заказ!')
rp.AddTerm('HitPriceLimit', 'Цены на заказ должны быть от # и до #.')
rp.AddTerm('HitTimer', 'Вы не можете нанести удар в течении # секунд.')
rp.AddTerm('MultiHit', 'Вы не можете заказать одного и того же человека так часто!')
rp.AddTerm('BountyIncrease', 'Вы увеличили вознаграждение за # на #.')
rp.AddTerm('HitPlaced', 'Вы сделали заказ на # за #.')
rp.AddTerm('HitmanFailed', 'Вы потерпели неудачу в качестве киллера!')
rp.AddTerm('EmployeeChangedJob', 'Ваш наниматель изменил работу!')
rp.AddTerm('EmployeeChangedJobYou', 'Ваш контракт был отменён потому, что вы сменили работу!')
rp.AddTerm('EmployeeDied', 'Ваша цель умерла!')
rp.AddTerm('EmployeeDiedYou', 'Ваш контракт был отменён потому что, Вы - умерли!')
rp.AddTerm('EmployerDied', 'Ваш наниматель умер!')
rp.AddTerm('EmployerDiedYou', 'Ваш работник уволен потому, что вы умерли.')
rp.AddTerm('EmployeeLeft', 'Ваша цель отключилась!')
rp.AddTerm('EmployerLeft', 'Ваш наниматель отключился!')
rp.AddTerm('PlayerNotHirable', '# не может быть нанят.')
rp.AddTerm('EmployeeTriedEmploying', 'В данный момент Вы ищете работу. Вы не можете нанять рабочего !')
rp.AddTerm('HasEmployee', 'Вы уже наёмный работник!')
rp.AddTerm('AlreadyEmployed', 'Вы уже нанят!')
rp.AddTerm('CannotAffordEmployee', 'Вы не можете нанять!')
rp.AddTerm('EmployRequestSent', '# отправил Вам запрос на найм.')
rp.AddTerm('YouHired', 'Вас нанял # для #.')
rp.AddTerm('YouAreHired', '# нанял Вас для #.')
rp.AddTerm('EmployRequestDen', '# отменил вашу заявку на работу.')
rp.AddTerm('EmployeeFired', 'Вы уволены #.')
rp.AddTerm('EmployeeFiredYou', '# Уволил вас!')
rp.AddTerm('EmployeeQuit', '#Вышел с работы вместе с вами!')
rp.AddTerm('EmployeeQuitYou', 'Вы ушли с работы #.')
rp.AddTerm('CannotTool', 'Недостаточно прав использовать "#" инструмент!')
rp.AddTerm('DupeRestrictedEnts', 'Вы не можете создавать дупликаты этих объектов!')
rp.AddTerm('WhitelistFull', ' Белый Список полон #/750')
rp.AddTerm('CacheFull', 'Модель Кэша заполнена #/100!')
rp.AddTerm('PropWhitelisted', '# добавлен в Белый Список #.')
rp.AddTerm('PropBlacklisted', '# был помещен в Черный Список #.')
rp.AddTerm('PPTargNotFound', 'Цель не найдена !')
rp.AddTerm('UnsharedPropsYou', 'Вы отменили доступ к своим пропам для #.')
rp.AddTerm('UnsharedProps', '# отменил вам доступ к своим пропам.')
rp.AddTerm('SharedPropsYou', 'Вы открыли доступ к своим пропам для  #.')
rp.AddTerm('SharedProps', '# Предоставил доступ к своим пропам для вас.')
rp.AddTerm('PPGroupSet', '# был добавлен в группу # by #.')
rp.AddTerm('PropNotWhitelisted', '# не в вайтлисте!')
rp.AddTerm('NoPMResponder', 'Там никого нет чтобы ответить')
rp.AddTerm('CannotDestroyWeapon', 'Вы не можете уничтожить это оружие!')
rp.AddTerm('YourEntDestroyed', 'Ваше # было уничтожено!')
rp.AddTerm('InvalidURL', 'не правильный URL!')
rp.AddTerm('VideoFailed', 'Не удалось загрузить видео: #.')
rp.AddTerm('FoodLimitReached', 'Вы достигли лимита еды!')
rp.AddTerm('BoughtFoodProduction', 'Вы заплатили # за продукты.')
rp.AddTerm('SoldFoodNoProf', 'Вы продали еду и не получили денег, но заработали 3 Кармы.')
rp.AddTerm('SoldFood', 'Вы продали еду и заработали # и получили  1 карму.')
rp.AddTerm('BoughtFood', 'Вы купили еду для #.')
rp.AddTerm('ThereIsACook', 'Есть повар. Вы не можете сделать этого!')
rp.AddTerm('EmptyShipment', 'Там нет товаров.')
rp.AddTerm('GCMessageLimit', 'Ваше сообщение должно быть больше чем 1 буква!')
rp.AddTerm('CantSuicideJail', 'Вы не можете покончить жизнь самоубийством в тюрьме.')
rp.AddTerm('CantSuicideWanted', 'Вы не можете покончить жизнь самоубийством пока вы в розыске .')
rp.AddTerm('CantSuicideFrozen', 'Вы не можете покончить жизнь самоубийством пока вы freeze.')
rp.AddTerm('CantSuicideLiveFor', 'Вам ещё долго жить!')
rp.AddTerm('YouSuicided', 'Вы опозорили свою семью!')
rp.AddTerm('CantPurchaseUpgrade', 'Вы не можете купить это. #')
rp.AddTerm('RPItemBought', 'Вы купили # за #.')
rp.AddTerm('CantAdminCleanup', 'Вы не можете использовать админскую очистку!')
rp.AddTerm('MayorHasDied', 'Мэр мёртв!')
rp.AddTerm('YouWereBailed', '# освободил тебя из тюрьмы!')
rp.AddTerm('ArmorLabProfit', 'Вы заработали $# из своей armor lab.')
rp.AddTerm('BoughtArmor', 'Вы купили Броне-Лабу за $#.')
rp.AddTerm('ArmorLabExploded', 'Ваша Броне-Лаба взорвалась!')
rp.AddTerm('ChequeFound', 'Вы нашёли # в чеке записанном на тебя #.')
rp.AddTerm('ChequeMadeTo', '"Этот чек сделан к  #.')
rp.AddTerm('ChequeTorn', 'Вы разорвали чек.')
rp.AddTerm('MoneyFound', 'Вы нашли $#!')
rp.AddTerm('MustBeHobo', 'Только бомжи могут это делать!')
rp.AddTerm('AlreadyDisguised', 'Вы уже замаскированы!')
rp.AddTerm('GunLicenseActive', 'Вы активировали лицензию на оружие.')
rp.AddTerm('YouGotAIDS', 'Вы заразились сифилисом.')
rp.AddTerm('YouGotHerpes', 'Вы заразились герпесом от иглы.')
rp.AddTerm('STDCured', 'Вы вылечились от сифилиса.')
rp.AddTerm('NowDisguised', 'Вы замаскированы как #.')
rp.AddTerm('NowDisguisedTime', 'Вы замаскированы как # на  #.')
rp.AddTerm('DisguiseWorn', 'Ваша маскировка закончилась.')
rp.AddTerm('DisguiseLimit', 'Вы не можете маскироваться ещё # минут.')
rp.AddTerm('MedLabProfit', 'Вы заработали $# на своей Мед-Лабу.')
rp.AddTerm('BoughtHealth', 'Вы купили здоровье за $#.')
rp.AddTerm('MedLabExploded', 'Ваша Мед-Лаба взорвалась!')
rp.AddTerm('KeypadControlsX', 'Этот кейпад контролирует # объект.')
rp.AddTerm('EntityControlledByX', 'Этот объект под контролем  # кейпада.')
rp.AddTerm('VoteAlone', 'Вы выйграли выборы поскольку были единственным кандидатом.')
rp.AddTerm('BannedFromJob', 'В настоящее время эта работа недоступна для вас.')
rp.AddTerm('VotedTooSoon', 'Пожалуйста, подождите # секунд чтобы начать голосование.')
rp.AddTerm('AlreadyThisJob', 'Вы уже на этой работе!')
rp.AddTerm('JobLimit', 'Лимит команды достигнут.')
rp.AddTerm('RegisteredForVote', 'Вы зарегистрированы на предстоящие выборы!')
rp.AddTerm('AlreadyVoting', 'Выборы уже начались. Вы опоздали!')
rp.AddTerm('JobNeedsAdmin', 'Вы должны быть moderator+ для этой работы.')
rp.AddTerm('JobNeedsSA', 'Вы должны быть SA+ для этой работы.')
rp.AddTerm('JobNeedsBanned', 'Ты должен быть забанен на сервере чтобы получить этот класс')
rp.AddTerm('IncorrectJob', 'У вас не та работа чтобы сделать это!')
rp.AddTerm('VoteStarted', 'Голосование создано.')
rp.AddTerm('CannotJob', 'Вы не можете изменить работу прямо сейчас.')
rp.AddTerm('JobLenShort', 'Название работы должно быть больше чем # буква.')
rp.AddTerm('JobLenLong', 'Название работы должно быть меньше чем  # букв.')
rp.AddTerm('CannotPurchaseItem', 'Вы не допущены к покупке этого предмета.')
rp.AddTerm('ItemLimit', 'Вы достигли # лимит.')
rp.AddTerm('ItemUnavailable', 'Эта вещь недоступна.')
rp.AddTerm('UnableToItem', 'Вы не в состоянии купить эту вещь.')
rp.AddTerm('ShipmentCooldown', 'Подождите прежде чем спавнить товар.')
rp.AddTerm('MedicExists', 'Вы не можете купить HP потому, что есть медик.')
rp.AddTerm('HealthIsFull', 'Ваше здоровье уже полное!')
rp.AddTerm('CannotDropWeapon', 'Вы не можете выкинуть это оружие!')
rp.AddTerm('LookAtEntity', 'Вы дожны смотреть на объект!')
rp.AddTerm('CannotSetPrice', 'Вы не можете установить цену на этот объект !')
rp.AddTerm('AnalProlapse', 'Вы перенапрягли анус и умерли от пролапса.')
rp.AddTerm('NoMorePoo', 'У тебя больше нет каках !')
rp.AddTerm('NotARapist', 'Вы не насильник.')
rp.AddTerm('RapeNPC', 'Вы не можете насиловать NPC.')
rp.AddTerm('RapeFailed', 'Попытка изнасилования провалена!')
rp.AddTerm('RapeAttempted', 'Кто-то пытается вторгнуться в вашу жопу.')
rp.AddTerm('Raped', 'Вас изнасиловал #, засадив вам прямо в зад.')
rp.AddTerm('YouAreRaped', 'Кто-то вторгается в ваш зад.')
rp.AddTerm('AnalProlapseShort', 'Вы умерли от анального пролапса.')
rp.AddTerm('DickFellOff', 'Ваш член отвалился.')
rp.AddTerm('CannotVote', 'Вы не можете голосовать.')
rp.AddTerm('CantDoThis', 'Вы не можете сделать это.')
rp.AddTerm('BaitingRule', 'Это не по правилам.')
rp.AddTerm('FoundNothing', 'Вы ничего не нашли.')
rp.AddTerm('RobberyAttempt', 'Вы чувствуете лёгкое движение в кармане.')
rp.AddTerm('RobberyFailed', 'Ограбление провалено!')
rp.AddTerm('YouRobbed', 'Вы украли $#!')
rp.AddTerm('YouAreRobbed', 'Ваш карман облегчился.')
rp.AddTerm('NoteUpdated', 'Текст не обновлен.')
rp.AddTerm('USENote', 'Нажмите использовать чтобы редактировать текст.')
rp.AddTerm('OrgYouAreStuck', 'Вы застряли! >:)')
rp.AddTerm('OrgYourRank', '# установил ваш ранг \'#\'.')
rp.AddTerm('OrgSetRank', '# добавлен \'#\'.')
rp.AddTerm('OrgUnknownRank', 'неизвестный ранг \'#\'.')
rp.AddTerm('OrgRankRename', 'Ранг \'#\' переименован в \'#\'.')
rp.AddTerm('OrgReorderLimit', 'Вы не можете изменить Высший и Низший ранги.')
rp.AddTerm('OrgRankUpdated', 'Ранг \'#\' обновлен.')
rp.AddTerm('OrgMaxRanks', 'Максимальный ранг достигнут.')
rp.AddTerm('OrgRankCreated', 'Ранг \'#\' Создан.')
rp.AddTerm('OrgDeleteLimit', 'Вы не можете удалить высший и низший ранг.')
rp.AddTerm('OrgRankDelete', 'Ранг \'#\' удалён.')
rp.AddTerm('OrgBannerUpdated', 'Банер обновлён.')
rp.AddTerm('FadeDoorCreated', 'Fading door создан.')
rp.AddTerm('FadeDoorCreatedExtra', 'Fading door создан. Теперь, правый клик чтобы создать кейпад.')
rp.AddTerm('InvalidPassword', 'неверный пароль!')
rp.AddTerm('KeypadHoldLength', 'Время удержание должно быть не менее # секунд.')
rp.AddTerm('KeypadCreated', 'Кейпад создан.')
rp.AddTerm('SboxPropLimit', 'Вы достигли лимита пропов!')
rp.AddTerm('SboxXLimit', 'Вы достигли # лимит')
-- Entities folder
rp.AddTerm('ArcadeMachineUse', 'Приготовьтесь к игре!')
rp.AddTerm('PlayerNotInJail', '# не в тюрьме.')
rp.AddTerm('PlayerFuckedBailing', 'Ты придурок, копы у тебя на хвосте!')
rp.AddTerm('PlayerBailedPlayer', '# заплатил за вас выкуп #.')
rp.AddTerm('PlayerTookDonationBox', 'Вы взяли #.')
rp.AddTerm('YouDontOwnThis', 'Вы не владеете этим!')
rp.AddTerm('PlayerReceivedDonationBox', 'Кто-то пожертвовал # в вашу коробку для пожертвования.')
rp.AddTerm('DrugLabExploded', 'Ваша нарко-лаборатория взорвалась!')
rp.AddTerm('PlayerNotWanted', 'Этот игрок не разыскивается!')
rp.AddTerm('PlayerTookMoneyBasket', 'Вы взяли #.')
rp.AddTerm('PrinterIsFull', 'Этот принтер полон чернилами!')
rp.AddTerm('PrinterRefilled', 'Вы заправили принтер за #.')
rp.AddTerm('PrinterExploded', 'Ваш принтер взорвался!')
rp.AddTerm('PlayerSoldDrugs', 'Вы продали # за #.')
-- Weapons folder
rp.AddTerm('ArrestBatonBonus', 'Вы заработали # бонус за уничтожение нелегального объекта.')
rp.AddTerm('ArrestBatonArrested', 'Вас арестовал #.')
rp.AddTerm('ArrestBatonYouArrested', 'Вы арестовали # и заработал 2 кармы.')
rp.AddTerm('PlayerRangDoorbell', 'Кто-то звонит в ваш дверной звонок.')
rp.AddTerm('KeysCooldown', 'Пожалуйста, подождите прежде чем закрывать дверь')
rp.AddTerm('UnarrestBatonTarg', 'Вас выпустил из тюрьмы #.')
rp.AddTerm('UnarrestBatonOwn', 'Вы освобождены #.')
rp.AddTerm('RiotShieldInSpawn', 'Пожалуста, покиньте спавн чтобы использовать этот щит!')
rp.AddTerm('HatPurchased', 'Вы заплатили # для #.')
rp.AddTerm('HatEquipped', 'Аксессуар надет!')
rp.AddTerm('HatRemoved', 'Шапка снята!')
rp.AddTerm('BURGHungerImmune', 'У вас имунитет к голоду пока твы не умрёте!')
rp.AddTerm('BURGNotPeople', 'Глупый бургер, бургер не человек!')

rp.AddTerm('WantedReasons', {'Убийство', 'Нелегальное оружие', 'Нанесение увечий', 'Нелегальные предметы'})

rp.AddTerm('KarmaAdeed', 'Господь отпустил ваши грехи!')
rp.AddTerm('KarmaCooldown', 'Вашу праведность стоило бы доказать делом!')
rp.AddTerm('GoodKarmaGain', 'Последнее время вы вели праведный образ жизни и получили # кармы!')


rp.AddTerm('nu.vehicleNotOwned', 'Вы не являетесь владельцем этого транспортного средства!')
rp.AddTerm('nu.vehicleSold', 'Вы продали # за $# !')
rp.AddTerm('nu.vehicleBought', 'Вы купили # за $#!')
rp.AddTerm('nu.vehicleReturned',  'Вы вернули свою машину!')
rp.AddTerm('nu.returnVehicleFirst', 'Вам нужно вернуть своё транспортное средство прежде чем брать другое!')
rp.AddTerm('nu.vehicleRestricted', 'Вы не можете спавнить этот автомобиль')
rp.AddTerm('nu.noMoneyForFee', 'У вас недостаточно средств, чтобы заплатить за спавн автомобиля.')
rp.AddTerm('nu.spawnVehicleFeeMsg', 'Вы заплатили $# за спавн #')
rp.AddTerm('nu.vehicleGranted', 'Вам дали автомобиль: # на #!')
rp.AddTerm('nu.vehicleRevoked', 'Вы забрали у # право на #!')
rp.AddTerm('nu.vehiclesForceReturned', 'Все ваши машины были возвращены #!')
rp.AddTerm('nu.alreadyOwned', 'У вас есть уже этот автомобиль!')
rp.AddTerm('nu.notEnoughMoney', 'У вас нет денег для того, чтобы купить этот автомобиль!')
rp.AddTerm('nu.spawn', 'Доставить')
rp.AddTerm('nu.nu.return', 'Вернуть')
rp.AddTerm('nu.purchase', 'Купить')
rp.AddTerm('nu.sell', 'Продать')
rp.AddTerm('nu.manager', 'Менеджер')
rp.AddTerm('nu.mods', 'Тюннинг')
rp.AddTerm('nu.paint', 'Цвет')
rp.AddTerm('nu.selectVehicleFirst', 'Сперва выберите автомобиль!')
rp.AddTerm('nu.saleEndsIn', 'Продам за: #')
rp.AddTerm('nu.shop','Магазин')
rp.AddTerm('nu.searchByTags', 'Поиск..')

rp.AddTerm('BankReady', 'В банк завезли деньги, интересно, попробует ли их кто-то украсть...')
rp.AddTerm('BankRobberyStarted', 'Грабители ворвались в хранилище банка, остановите их!')
rp.AddTerm('BankFillingCases', 'Началось наполнение кейсов деньгами, отнеси их к машине, когда посчитаешь, что тебе хватит!')
rp.AddTerm('BankRobberyInProgress', 'Банк грабят, немедленно остановите грабителей!')
rp.AddTerm('BankBringCases', 'Скорее тащи кейсы в машину, я сваливаю через # секунд!')
rp.AddTerm('BankRobberyEnd', 'Всё, я ухеал. Ты упустил свой шанс.')
rp.AddTerm('BankCaseReturnReward', 'Ты вернул деньги в банк и получил $# и # кармы!')
rp.AddTerm('BankCaseStealReward', 'Отлично, вот твои $#!')
rp.AddTerm('BankRobbersWon', 'Ограбление закончено, грабители одержали победу')
rp.AddTerm('BankDraw', 'Ограбление закночилось ничьей')
rp.AddTerm('BankPoliceWon', 'Ограбление закончено, полиция победила бандитов')
rp.AddTerm('BankBringCaseToBank', 'Отнеси кейс обратно в банк, если хочешь получить награду!')
rp.AddTerm('BankBringCaseToCar', 'Тащи кейс к машине, если хочешь получить награду!')
rp.AddTerm('BankProtectCar', 'Не дай грабителям отнести кейс к машине!')
rp.AddTerm('NotAllowedInBank', '# не разрешен в банке!')

